import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

import {
  computeLineHt,
  computeLineTtc,
  computeLineVatAmount,
  computeTotalsFromLines,
} from '@/lib/invoice-calculations';
import {
  formatClientPhysicalAddress,
  formatEmitterPhysicalAddress,
} from '@/lib/invoice-address';
import type { InvoiceFormValues } from '@/lib/invoice-types';

/**
 * SHA-256 of PDF bytes as 0x-prefixed 32-byte hex (matches contract `bytes32` invoice hash).
 */
export async function pdfBlobToBytes32(pdf: Blob): Promise<`0x${string}`> {
  const buf = await pdf.arrayBuffer();
  const hashBuffer = await crypto.subtle.digest('SHA-256', buf);
  const bytes = new Uint8Array(hashBuffer);
  let hex = '0x';
  for (let i = 0; i < bytes.length; i++) {
    hex += bytes[i]!.toString(16).padStart(2, '0');
  }
  return hex as `0x${string}`;
}

export async function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const r = reader.result;
      if (typeof r !== 'string') {
        reject(new Error('read failed'));
        return;
      }
      const base64 = r.split(',')[1];
      if (!base64) reject(new Error('invalid data url'));
      else resolve(base64);
    };
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(blob);
  });
}

// ── PDF layout constants (A4: 595.28 x 841.89 pt) ──────────────────────────

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y = MARGIN;
const COLOR_BLACK = rgb(0, 0, 0);
const COLOR_GRAY = rgb(0.45, 0.45, 0.45);
const COLOR_LIGHT_GRAY = rgb(0.7, 0.7, 0.7);
const COLOR_LINE = rgb(0.85, 0.85, 0.85);

function fmtMoney(n: number, currency: string): string {
  const iso = currency === 'EURC' ? 'EUR' : 'USD';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: iso,
    minimumFractionDigits: 2,
  }).format(n);
}

function buildFacturXml(data: InvoiceFormValues, totalTtc: number): string {
  const iso = data.currency === 'EURC' ? 'EUR' : 'USD';
  return `<?xml version="1.0" encoding="UTF-8"?>
<rsm:CrossIndustryInvoice xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100">
  <rsm:ExchangedDocument>
    <ram:ID>${escapeXml(data.invoiceNumber)}</ram:ID>
    <ram:TypeCode>380</ram:TypeCode>
  </rsm:ExchangedDocument>
  <rsm:SupplyChainTradeTransaction>
    <ram:ApplicableHeaderTradeSettlement>
      <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
        <ram:GrandTotalAmount currencyID="${iso}">${totalTtc.toFixed(2)}</ram:GrandTotalAmount>
      </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
    </ram:ApplicableHeaderTradeSettlement>
  </rsm:SupplyChainTradeTransaction>
</rsm:CrossIndustryInvoice>`.trim();
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Build a certified invoice PDF programmatically with an embedded Factur-X XML attachment.
 * Returns a Blob ready for hashing and on-chain submission.
 */
export async function generateInvoicePdf(
  data: InvoiceFormValues,
  emitterWorldIdNullifier?: string | null,
): Promise<Blob> {
  const pdfDoc = await PDFDocument.create();
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const { totalHt, tvaAmount, totalTtc } = computeTotalsFromLines(data.lines);

  let page = pdfDoc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;
  let pageCount = 1;

  function ensureSpace(needed: number) {
    if (y - needed < FOOTER_Y + 30) {
      drawFooter(page, pageCount);
      page = pdfDoc.addPage([PAGE_W, PAGE_H]);
      pageCount++;
      y = PAGE_H - MARGIN;
      drawSlimHeader();
    }
  }

  function drawHLine(atY: number) {
    page.drawLine({
      start: { x: MARGIN, y: atY },
      end: { x: PAGE_W - MARGIN, y: atY },
      thickness: 0.5,
      color: COLOR_LINE,
    });
  }

  function drawFooter(p: typeof page, _num: number) {
    p.drawLine({
      start: { x: MARGIN, y: FOOTER_Y + 12 },
      end: { x: PAGE_W - MARGIN, y: FOOTER_Y + 12 },
      thickness: 0.5,
      color: COLOR_LINE,
    });
    p.drawText('ONVO', {
      x: MARGIN,
      y: FOOTER_Y,
      size: 7,
      font: fontBold,
      color: COLOR_LIGHT_GRAY,
    });
    const footerText =
      'Document generated by Onvo \u2014 on-chain hash at issuance.';
    p.drawText(footerText, {
      x: MARGIN + 28,
      y: FOOTER_Y,
      size: 7,
      font: fontRegular,
      color: COLOR_LIGHT_GRAY,
    });
  }

  function drawSlimHeader() {
    page.drawText(data.invoiceNumber || 'INVOICE', {
      x: MARGIN,
      y: y,
      size: 9,
      font: fontBold,
      color: COLOR_BLACK,
    });
    page.drawText(`${data.issueDate}  \u2014  ${data.currency}`, {
      x: PAGE_W - MARGIN - 120,
      y: y,
      size: 8,
      font: fontRegular,
      color: COLOR_GRAY,
    });
    y -= 20;
    drawHLine(y);
    y -= 15;
  }

  // ── 1. Invoice header ──

  page.drawText('INVOICE', {
    x: MARGIN,
    y,
    size: 22,
    font: fontBold,
    color: COLOR_BLACK,
  });

  const docNo = data.invoiceNumber?.trim() || '—';
  page.drawText(`Document no.: ${docNo}`, {
    x: MARGIN,
    y: y - 18,
    size: 10,
    font: fontRegular,
    color: COLOR_GRAY,
  });

  const rightX = PAGE_W - MARGIN;

  const issuedLabel = `Issued: ${data.issueDate}`;
  const issuedWidth = fontRegular.widthOfTextAtSize(issuedLabel, 9);
  page.drawText(issuedLabel, {
    x: rightX - issuedWidth,
    y,
    size: 9,
    font: fontRegular,
    color: COLOR_GRAY,
  });

  const dueLabel = `Due: ${data.dueDate}`;
  const dueWidth = fontRegular.widthOfTextAtSize(dueLabel, 9);
  page.drawText(dueLabel, {
    x: rightX - dueWidth,
    y: y - 13,
    size: 9,
    font: fontRegular,
    color: COLOR_GRAY,
  });

  const currencyWidth = fontRegular.widthOfTextAtSize(data.currency, 8);
  page.drawText(data.currency, {
    x: rightX - currencyWidth,
    y: y - 28,
    size: 8,
    font: fontRegular,
    color: COLOR_LIGHT_GRAY,
  });

  y -= 50;
  drawHLine(y);
  y -= 25;

  // ── 2. Emitter + Client blocks ──

  const colW = CONTENT_W / 2 - 10;
  const emitterX = MARGIN;
  const clientX = MARGIN + colW + 20;

  function drawInfoBlock(
    x: number,
    label: string,
    name: string,
    address: string,
    extras: string[],
  ) {
    page.drawText(label, {
      x,
      y,
      size: 7,
      font: fontBold,
      color: COLOR_GRAY,
    });
    let blockY = y - 14;
    page.drawText(name, {
      x,
      y: blockY,
      size: 10,
      font: fontBold,
      color: COLOR_BLACK,
    });
    blockY -= 14;
    for (const line of address.split('\n').filter(Boolean)) {
      page.drawText(line, {
        x,
        y: blockY,
        size: 9,
        font: fontRegular,
        color: COLOR_GRAY,
      });
      blockY -= 12;
    }
    for (const extra of extras.filter(Boolean)) {
      page.drawText(extra, {
        x,
        y: blockY,
        size: 8,
        font: fontRegular,
        color: COLOR_LIGHT_GRAY,
      });
      blockY -= 11;
    }
    return blockY;
  }

  const emitterExtras: string[] = [];
  if (data.emitterSiret) emitterExtras.push(`SIRET: ${data.emitterSiret}`);
  if (data.emitterVatNumber?.trim())
    emitterExtras.push(`VAT: ${data.emitterVatNumber.trim()}`);
  if (data.emitterEmail) emitterExtras.push(data.emitterEmail);
  if (emitterWorldIdNullifier?.trim())
    emitterExtras.push(`World ID: ${emitterWorldIdNullifier.trim()}`);

  const clientExtras: string[] = [];
  if (data.clientEmail) clientExtras.push(data.clientEmail);

  const emitterBottom = drawInfoBlock(
    emitterX,
    'FROM',
    data.emitterName,
    formatEmitterPhysicalAddress(data),
    emitterExtras,
  );
  const clientBottom = drawInfoBlock(
    clientX,
    'TO',
    data.clientName,
    formatClientPhysicalAddress(data),
    clientExtras,
  );

  y = Math.min(emitterBottom, clientBottom) - 20;
  ensureSpace(30);

  // ── 3. Line items table ──

  const cols = [
    { label: 'Description', w: 160, align: 'left' as const },
    { label: 'Qty', w: 40, align: 'right' as const },
    { label: 'Unit HT', w: 70, align: 'right' as const },
    { label: 'VAT %', w: 50, align: 'right' as const },
    { label: 'HT', w: 65, align: 'right' as const },
    { label: 'VAT', w: 55, align: 'right' as const },
    { label: 'TTC', w: 55, align: 'right' as const },
  ];

  function drawTableHeader() {
    let cx = MARGIN;
    for (const col of cols) {
      const text = col.label;
      if (col.align === 'right') {
        const tw = fontBold.widthOfTextAtSize(text, 7);
        page.drawText(text, {
          x: cx + col.w - tw,
          y,
          size: 7,
          font: fontBold,
          color: COLOR_GRAY,
        });
      } else {
        page.drawText(text, {
          x: cx,
          y,
          size: 7,
          font: fontBold,
          color: COLOR_GRAY,
        });
      }
      cx += col.w;
    }
    y -= 8;
    drawHLine(y);
    y -= 14;
  }

  drawTableHeader();

  for (const line of data.lines) {
    ensureSpace(20);
    const ht = computeLineHt(line);
    const vat = computeLineVatAmount(line);
    const ttc = computeLineTtc(line);

    const values = [
      line.description,
      String(line.quantity),
      fmtMoney(line.unitPrice, data.currency),
      `${line.vatPercent}%`,
      fmtMoney(ht, data.currency),
      fmtMoney(vat, data.currency),
      fmtMoney(ttc, data.currency),
    ];

    let cx = MARGIN;
    for (let i = 0; i < cols.length; i++) {
      const col = cols[i]!;
      const val = values[i]!;
      const fontSize = i === 0 ? 9 : 8;
      const font = i === 0 ? fontRegular : fontRegular;
      const color = i === 0 || i >= 4 ? COLOR_BLACK : COLOR_GRAY;

      const truncated =
        i === 0 ? truncateText(val, col.w - 4, fontRegular, fontSize) : val;

      if (col.align === 'right') {
        const tw = font.widthOfTextAtSize(truncated, fontSize);
        page.drawText(truncated, {
          x: cx + col.w - tw,
          y,
          size: fontSize,
          font,
          color,
        });
      } else {
        page.drawText(truncated, {
          x: cx,
          y,
          size: fontSize,
          font,
          color,
        });
      }
      cx += col.w;
    }
    y -= 6;
    drawHLine(y);
    y -= 14;
  }

  // ── 4. Totals ──

  ensureSpace(60);
  y -= 5;
  const totalsX = PAGE_W - MARGIN - 180;

  function drawTotalRow(
    label: string,
    value: string,
    bold = false,
    underline = false,
  ) {
    const f = bold ? fontBold : fontRegular;
    const sz = bold ? 11 : 9;
    page.drawText(label, {
      x: totalsX,
      y,
      size: sz,
      font: f,
      color: bold ? COLOR_BLACK : COLOR_GRAY,
    });
    const vw = f.widthOfTextAtSize(value, sz);
    page.drawText(value, {
      x: PAGE_W - MARGIN - vw,
      y,
      size: sz,
      font: f,
      color: COLOR_BLACK,
    });
    if (underline) {
      y -= 4;
      page.drawLine({
        start: { x: totalsX, y },
        end: { x: PAGE_W - MARGIN, y },
        thickness: 0.5,
        color: COLOR_LINE,
      });
    }
    y -= 16;
  }

  drawTotalRow('Total HT', fmtMoney(totalHt, data.currency));
  drawTotalRow('Total VAT', fmtMoney(tvaAmount, data.currency));
  drawTotalRow('Total TTC', fmtMoney(totalTtc, data.currency), true, true);

  // ── 5. Notes ──

  if (data.notes?.trim()) {
    ensureSpace(40);
    y -= 10;
    drawHLine(y);
    y -= 15;
    page.drawText('NOTES', {
      x: MARGIN,
      y,
      size: 7,
      font: fontBold,
      color: COLOR_GRAY,
    });
    y -= 14;
    const noteLines = data.notes.split('\n');
    for (const nl of noteLines) {
      ensureSpace(14);
      page.drawText(nl, {
        x: MARGIN,
        y,
        size: 9,
        font: fontRegular,
        color: COLOR_GRAY,
      });
      y -= 12;
    }
  }

  // ── 6. Footer on last page ──

  drawFooter(page, pageCount);

  // ── 7. Attach Factur-X XML ──

  const xml = buildFacturXml(data, totalTtc);
  const xmlBytes = new TextEncoder().encode(xml);
  await pdfDoc.attach(xmlBytes, 'factur-x.xml', {
    mimeType: 'text/xml',
    description: 'Factur-X Basic invoice data',
    creationDate: new Date(),
    modificationDate: new Date(),
  });

  // ── 8. Save ──

  const pdfBytes = await pdfDoc.save();
  return new Blob([pdfBytes.buffer as ArrayBuffer], {
    type: 'application/pdf',
  });
}

function truncateText(
  text: string,
  maxWidth: number,
  font: { widthOfTextAtSize(t: string, s: number): number },
  size: number,
): string {
  if (font.widthOfTextAtSize(text, size) <= maxWidth) return text;
  let truncated = text;
  while (
    truncated.length > 0 &&
    font.widthOfTextAtSize(truncated + '\u2026', size) > maxWidth
  ) {
    truncated = truncated.slice(0, -1);
  }
  return truncated + '\u2026';
}
